### ISSUE TITLE
Static error at html on line 1 column 7 of colors.xsl:

### ISSUE THREAD

**Issue by Shalu-SS** [transpect/mml2tex#24]
java -jar saxon9he.jar -s:eq.xml -xsl:/home/User/mml2tex/xsl/invoke-mml2tex.xsl
Static error at html on line 1 column 7 of colors.xsl:
  XTSE0150: The supplied file does not appear to be a stylesheet
Static error at xsl:import on line 10 column 35 of invoke-mml2tex.xsl:
  XTSE0165: Reported 1 error in imported stylesheet module
Errors were reported during stylesheet compilation

**Comment by mkraetke** [comment]
Hi Shalu,

mml2tex is a library rather than a standalone stylesheet. If you intend to run mml2tex standalone, you need to include the dependencies, add a proper XML catalog and invoke Saxon with XML resolver support. If you carefully follow the steps below, mml2tex should work as expected.

```
mkdir myProjectDir
cd myProjectDir
git clone git@github.com:transpect/mml2tex.git
git clone git@github.com:transpect/xslt-util.git
mkdir xmlcatalog
touch xmlcatalog/catalog.xml
```

Then edit `xmlcatalog/catalog.xml` with your text editor of choice:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <nextCatalog catalog="../xslt-util/xmlcatalog/catalog.xml"/>
</catalog>
```

Download [Apache XML Commons Resolver](https://xerces.apache.org/mirrors.cgi) and invoke Saxon:

```
java -cp "C:/cygwin64/home/kraetke/xmltools/saxon/saxon9he.jar;C:/cygwin64/home/kraetke/xmltools/xml-commons-resolver/resolver.jar" \
-Dxml.catalog.files=C:/cygwin64/home/kraetke/myProjectDir/xmlcatalog/catalog.xml \
net.sf.saxon.Transform \
-catalog:xmlcatalog/catalog.xml \
-xsl:mml2tex/xsl/invoke-mml2tex.xsl \
-s:mml2tex/example/example.xml
```
Kind regards,
Martin
